name: Run Main.js on Push

on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '23.4.0'  # Specify the Node.js version you want to use

      - name: Install dependencies
        run: npm install --legacy-peer-deps --force  # Install any dependencies if you have a package.json

      - name: Run main.js
        run: node main.js  # Run your main.js file

